/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accruals/payroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Payroll */
        post: operations["payroll_api_accruals_payroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accruals/rollover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollover */
        post: operations["rollover_api_accruals_rollover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accruals/scheduled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scheduled */
        post: operations["scheduled_api_accruals_scheduled_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{assignment_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Assignment */
        post: operations["end_assignment_api_assignments__assignment_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/job-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Runs */
        get: operations["job_runs_api_audit_job_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/accruals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Accruals */
        post: operations["run_accruals_api_dev_accruals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/clock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Clock */
        post: operations["set_clock_api_dev_clock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/rollover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Rollover */
        post: operations["run_rollover_api_dev_rollover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_api_dev_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_api_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_api_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{employee_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Employee Assignments */
        get: operations["employee_assignments_api_employees__employee_id__assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{employee_id}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balances */
        get: operations["balances_api_employees__employee_id__balances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{employee_id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ledger */
        get: operations["ledger_api_employees__employee_id__ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report whether the API can reach PostgreSQL.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holidays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Holidays */
        get: operations["list_holidays_api_holidays_get"];
        put?: never;
        /** Add Holiday */
        post: operations["add_holiday_api_holidays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holidays/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Holidays */
        post: operations["sync_holidays_api_holidays_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policies */
        get: operations["policies_api_policies_get"];
        put?: never;
        /** Create Policy */
        post: operations["create_policy_api_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Policy */
        put: operations["update_policy_api_policies__policy_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{policy_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments */
        get: operations["list_assignments_api_policies__policy_id__assignments_get"];
        put?: never;
        /** Assign */
        post: operations["assign_api_policies__policy_id__assignments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{policy_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versions */
        get: operations["versions_api_policies__policy_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_api_requests_get"];
        put?: never;
        /** Submit */
        post: operations["submit_api_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_requests_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_requests__request_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_requests__request_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deny */
        post: operations["deny_api_requests__request_id__deny_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccrualMethod
         * @enum {string}
         */
        AccrualMethod: "TIME" | "HOURS_WORKED";
        /** AccrualRuleIn */
        AccrualRuleIn: {
            accrues_at?: components["schemas"]["AccruesAt"] | null;
            /** Amount */
            amount: number | string;
            frequency?: components["schemas"]["Schedule"] | null;
            method: components["schemas"]["AccrualMethod"];
            /**
             * Min Tenure Months
             * @default 0
             */
            min_tenure_months: number;
            /** Per Minutes Worked */
            per_minutes_worked?: number | null;
            unit: components["schemas"]["RateUnit"];
        };
        /** AccrualRuleOut */
        AccrualRuleOut: {
            accrues_at: components["schemas"]["AccruesAt"] | null;
            /** Amount */
            amount: string;
            frequency: components["schemas"]["Schedule"] | null;
            /** Id */
            id: string;
            method: components["schemas"]["AccrualMethod"];
            /** Min Tenure Months */
            min_tenure_months: number;
            /** Per Minutes Worked */
            per_minutes_worked: number | null;
            unit: components["schemas"]["RateUnit"];
        };
        /**
         * AccruesAt
         * @enum {string}
         */
        AccruesAt: "START_OF_PERIOD" | "END_OF_PERIOD";
        /** AssignIn */
        AssignIn: {
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Employee Ids */
            employee_ids: string[];
        };
        /** AssignmentOut */
        AssignmentOut: {
            /** Category Id */
            category_id: string;
            /** Created By */
            created_by: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /** Employee Id */
            employee_id: string;
            /** Employee Name */
            employee_name: string;
            /** Id */
            id: string;
            /** Policy Id */
            policy_id: string;
            /** Policy Name */
            policy_name: string;
        };
        /** BalanceOut */
        BalanceOut: {
            /** Available Minutes */
            available_minutes: number;
            /** Balance Minutes */
            balance_minutes: number;
            /** Category Id */
            category_id: string;
            /** Category Name */
            category_name: string;
            /** Day Minutes */
            day_minutes: number;
            /** Has Policy */
            has_policy: boolean;
            /** Is Unlimited */
            is_unlimited: boolean;
            /** Pending Hold Minutes */
            pending_hold_minutes: number;
            /** Policy Id */
            policy_id: string | null;
            /** Policy Name */
            policy_name: string | null;
        };
        /** CategoryCreateIn */
        CategoryCreateIn: {
            /** Icon */
            icon?: string | null;
            /** Name */
            name: string;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Icon */
            icon: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ClockIn */
        ClockIn: {
            /**
             * Current Date
             * Format: date
             */
            current_date: string;
        };
        /** DecisionIn */
        DecisionIn: {
            /** Note */
            note?: string | null;
        };
        /** EmployeeOut */
        EmployeeOut: {
            /** Email */
            email: string;
            /** Employment Type */
            employment_type: string;
            /** Id */
            id: string;
            /** Is Admin */
            is_admin: boolean;
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Work Minutes Per Day */
            work_minutes_per_day: number;
            /** Work State */
            work_state: string;
        };
        /** EndAssignmentIn */
        EndAssignmentIn: {
            /**
             * Effective To
             * Format: date
             */
            effective_to: string;
        };
        /**
         * EntryType
         * @enum {string}
         */
        EntryType: "ACCRUAL" | "FORFEITURE" | "CARRYOVER" | "EXPIRATION" | "REQUEST_DEBIT" | "REQUEST_REVERSAL";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HolidayIn */
        HolidayIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Name */
            name: string;
            /**
             * Observed
             * @default false
             */
            observed: boolean;
        };
        /** HolidayOut */
        HolidayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Observed */
            observed: boolean;
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "SCHEDULED" | "PAYROLL" | "ROLLOVER";
        /** JobRunOut */
        JobRunOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entries Created */
            entries_created: number;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            kind: components["schemas"]["JobKind"];
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
        };
        /** LedgerEntryOut */
        LedgerEntryOut: {
            /** Amount Minutes */
            amount_minutes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Effective Date
             * Format: date
             */
            effective_date: string;
            entry_type: components["schemas"]["EntryType"];
            /** Id */
            id: string;
            /** Note */
            note: string | null;
            /** Source Id */
            source_id: string;
            source_type: components["schemas"]["SourceType"];
        };
        /**
         * NewHireProration
         * @enum {string}
         */
        NewHireProration: "PRORATE" | "FULL" | "NONE";
        /** PayrollAccrualIn */
        PayrollAccrualIn: {
            /** Minutes By Employee */
            minutes_by_employee: {
                [key: string]: number;
            };
            /** Payroll Run Id */
            payroll_run_id: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
        };
        /** PolicyCreateIn */
        PolicyCreateIn: {
            /**
             * Allow Negative
             * @default false
             */
            allow_negative: boolean;
            /** Carryover Cap Minutes */
            carryover_cap_minutes?: number | null;
            /** Category Id */
            category_id: string;
            /**
             * Change Reason
             * @default Policy created
             */
            change_reason: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /**
             * Expires At Period End
             * @default false
             */
            expires_at_period_end: boolean;
            kind: components["schemas"]["PolicyKind"];
            /** Max Balance Minutes */
            max_balance_minutes?: number | null;
            /** Name */
            name: string;
            /**
             * Negative Floor Minutes
             * @default 0
             */
            negative_floor_minutes: number;
            /** @default PRORATE */
            new_hire_proration: components["schemas"]["NewHireProration"];
            /** Rules */
            rules?: components["schemas"]["AccrualRuleIn"][];
            /** @default NEXT_PERIOD */
            tenure_transition: components["schemas"]["TenureTransition"];
        };
        /**
         * PolicyKind
         * @enum {string}
         */
        PolicyKind: "UNLIMITED" | "ACCRUAL";
        /** PolicyOut */
        PolicyOut: {
            /** Category Id */
            category_id: string;
            /** Category Name */
            category_name: string;
            /** Created By */
            created_by: string;
            current_version: components["schemas"]["PolicyVersionOut"];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Version Count */
            version_count: number;
        };
        /** PolicyUpdateIn */
        PolicyUpdateIn: {
            /**
             * Allow Negative
             * @default false
             */
            allow_negative: boolean;
            /** Carryover Cap Minutes */
            carryover_cap_minutes?: number | null;
            /** Change Reason */
            change_reason: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /**
             * Expires At Period End
             * @default false
             */
            expires_at_period_end: boolean;
            kind: components["schemas"]["PolicyKind"];
            /** Max Balance Minutes */
            max_balance_minutes?: number | null;
            /** Name */
            name?: string | null;
            /**
             * Negative Floor Minutes
             * @default 0
             */
            negative_floor_minutes: number;
            /** @default PRORATE */
            new_hire_proration: components["schemas"]["NewHireProration"];
            /** Rules */
            rules?: components["schemas"]["AccrualRuleIn"][];
            /** @default NEXT_PERIOD */
            tenure_transition: components["schemas"]["TenureTransition"];
        };
        /** PolicyVersionOut */
        PolicyVersionOut: {
            /** Allow Negative */
            allow_negative: boolean;
            /** Carryover Cap Minutes */
            carryover_cap_minutes: number | null;
            /** Change Reason */
            change_reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Expires At Period End */
            expires_at_period_end: boolean;
            /** Id */
            id: string;
            kind: components["schemas"]["PolicyKind"];
            /** Max Balance Minutes */
            max_balance_minutes: number | null;
            /** Negative Floor Minutes */
            negative_floor_minutes: number;
            new_hire_proration: components["schemas"]["NewHireProration"];
            /** Rules */
            rules: components["schemas"]["AccrualRuleOut"][];
            tenure_transition: components["schemas"]["TenureTransition"];
            /** Version No */
            version_no: number;
        };
        /**
         * RateUnit
         * @enum {string}
         */
        RateUnit: "DAY" | "HOUR" | "MINUTE";
        /** RequestDayOut */
        RequestDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Minutes */
            minutes: number;
        };
        /** RequestEventOut */
        RequestEventOut: {
            /** Actor Id */
            actor_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            from_status: components["schemas"]["RequestStatus"] | null;
            /** Note */
            note: string | null;
            to_status: components["schemas"]["RequestStatus"];
        };
        /** RequestIn */
        RequestIn: {
            /** Category Id */
            category_id: string;
            /** Employee Id */
            employee_id: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Hours */
            hours?: number | null;
            /** Minutes */
            minutes?: number | null;
            /** Reason */
            reason: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** RequestPreviewOut */
        RequestPreviewOut: {
            /** Available Minutes */
            available_minutes: number;
            /** Days */
            days: components["schemas"]["RequestDayOut"][];
            /** Total Minutes */
            total_minutes: number;
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "PENDING" | "APPROVED" | "DENIED" | "CANCELLED";
        /**
         * Schedule
         * @enum {string}
         */
        Schedule: "DAILY" | "WEEKLY" | "SEMIMONTHLY" | "BIWEEKLY" | "MONTHLY" | "YEARLY";
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "SCHEDULED_ACCRUAL" | "PAYROLL_ACCRUAL" | "REQUEST" | "REQUEST_CANCELLATION" | "PERIOD_ROLLOVER";
        /**
         * TenureTransition
         * @enum {string}
         */
        TenureTransition: "NEXT_PERIOD";
        /** TimeOffRequestOut */
        TimeOffRequestOut: {
            /** Category Id */
            category_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days */
            days: components["schemas"]["RequestDayOut"][];
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Employee Id */
            employee_id: string;
            /** Employee Name */
            employee_name: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Events */
            events: components["schemas"]["RequestEventOut"][];
            /** Id */
            id: string;
            /** Is Partial Day */
            is_partial_day: boolean;
            /** Policy Id */
            policy_id: string;
            /** Reason */
            reason: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            status: components["schemas"]["RequestStatus"];
            /** Total Minutes */
            total_minutes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    payroll_api_accruals_payroll_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayrollAccrualIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollover_api_accruals_rollover_post: {
        parameters: {
            query: {
                as_of: string;
            };
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduled_api_accruals_scheduled_post: {
        parameters: {
            query: {
                as_of: string;
            };
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_assignment_api_assignments__assignment_id__end_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndAssignmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_runs_api_audit_job_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_categories_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_accruals_api_dev_accruals_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_clock_api_dev_clock_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClockIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_rollover_api_dev_rollover_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_api_dev_state_get: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_employees_api_employees_get: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_api_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    employee_assignments_api_employees__employee_id__assignments_get: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    balances_api_employees__employee_id__balances_get: {
        parameters: {
            query: {
                on_date: string;
            };
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ledger_api_employees__employee_id__ledger_get: {
        parameters: {
            query?: {
                policy_id?: string | null;
            };
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_holidays_api_holidays_get: {
        parameters: {
            query: {
                year: number;
            };
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HolidayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_holiday_api_holidays_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HolidayIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HolidayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_holidays_api_holidays_sync_post: {
        parameters: {
            query: {
                year: number;
            };
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HolidayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policies_api_policies_get: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_policy_api_policies_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy_api_policies__policy_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assignments_api_policies__policy_id__assignments_get: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_api_policies__policy_id__assignments_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    versions_api_policies__policy_id__versions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_api_requests_get: {
        parameters: {
            query?: {
                employee_id?: string | null;
                status?: components["schemas"]["RequestStatus"] | null;
            };
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffRequestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_requests_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_requests_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_requests__request_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_requests__request_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deny_api_requests__request_id__deny_post: {
        parameters: {
            query?: never;
            header?: {
                "x-actor-id"?: string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
